### ISSUE TITLE
White screen??!!

### ISSUE THREAD

**Issue by mayed505** [imjog/phimpme-iOS#1]
Hello, I have tried to install this xcode project on my phone.
It shows the splashscreen then goes into a white screen mode forever, it won't show anything after that.

**Comment by imjog** [comment]
@mayed505  yes, it is showing white screen because we didn't made any UI still. I will push some UI soon and then you can start working.

**Comment by mayed505** [comment]
Ahh, Thank you.
Can't wait to reskin that baby up!

**Comment by imjog** [comment]
@mayed505  good to know that!

**Comment by mayed505** [comment]
@imjog Would you help me with custom development? I own a hosting business and we can do some trades :)
I've some idea for you
I'll join your slack

**Comment by mayed505** [comment]
gitter*

**Comment by mayed505** [comment]
The project is done?

**Comment by imjog** [comment]
@mayed505 please do not spam here. I have to block you from commenting.

**Comment by mayed505** [comment]
@imjog How am I spamming? I'm asking about my issue which is "Is the project done?" because I've seen you update stuff 3 hours ago..

**Comment by imjog** [comment]
Which project is completed in 3 hours?

**Comment by mayed505** [comment]
No, I'm saying you have made updates to THIS project 3 hours ago. I thought you have finished it.
https://gyazo.com/597a32446c020230862735a7c6e44e4b

**Comment by imjog** [comment]
@mayed505 if you owning hosting business then you must also have learned to be professional, not cheap. Github issues is not place to talk about business.

**Comment by mayed505** [comment]
**Facepalm** you're going off topic.
https://gyazo.com/f570c71304261e8b1eb3388a3a6a387b
You aren't answering my question, I'm asking about this project if you have fixed that white screen issue this has nothing to do with my last request.
